# Python to Linux Web App on Azure
# Build your Python project and deploy it to Azure as a Linux Web App.
# Change python version to one thats appropriate for your application.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)

  # Python version: 3.10
  pythonVersion: '3.10'

stages:
- stage: Build
  displayName: Build app
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'
    - script: |
        pip install pdm
      displayName: 'Install pdm'
    - script: |
        pip install keyring
        pip install artifacts-keyring
      displayName: 'Install keyring'
    - script: |
        pdm install
      workingDirectory: $(projectRoot)
      displayName: "Install requirements"
      

- stage: DockerBuild
  displayName: 'Build Docker Image'
  jobs:
  - job: DockerBuildJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'costocksregistry'
        repository: 'backenda'
        command: 'build'
        

- stage: DockerBuildPush
  displayName: 'Buld and Push Docker Image'
  dependsOn: 
    - DockerBuild
  jobs:
  - job: DockerPushJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      condition: and(succeeded(), eq(variables['Build.Reason'], 'Manual'))
      inputs:
        containerRegistry: 'costocksregistry'
        repository: 'backenda'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'
      
